### ISSUE TITLE
Kubecost Addon fails with 1.25 K8s version in EKS Blueprints Patterns.

### ISSUE THREAD

**Issue by elamaran11** [kubecost/kubecost-ssp-addon#3]
Both our CDK EKS Blueprints Patterns using Kubecost fails because PSP support is removed in 1.25 and the addon still uses older version which uses PSP. Please see the error below and please fix it:

```bash
make pattern secure-ingress-cognito deploy secure-ingress-blueprint
6:10
0:00:53 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | secure-ingress-blu...t/Resource/Default
Received response status [FAILED] from custom resource. Message returned: Error: b'Release "kubecost-cost-analyzer" doe
s not exist. Installing it now.\nError: unable to build kubernetes objects from release manifest: [resource mapping not
found for name: "kubecost-cost-analyzer-grafana" namespace: "" from "": no matches for kind "PodSecurityPolicy" in vers
ion "policy/v1beta1"\nensure CRDs are installed first, resource mapping not found for name: "kubecost-cost-analyzer-psp
" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"\nensure CRDs are installed
first]\n'
Logs: /aws/lambda/secure-ingress-blueprint-awscdkaws-Handler886CB40B-1P89ryjaAEGj
at invokeUserFunction (/var/task/framework.js:2:6)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: e9d23421-9440-4d6d-b799-ba3f75baad1c)
10:00:55 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | secure-ingress-blueprint
The following resource(s) failed to create: [vpccniaddOn, secureingressblueprintchartkubecost466789EF, secureingressblu
eprintchartexternaldns9C936CCA, awsebscsidriveraddOn, corednsaddOn]. Rollback requested by user.
10:00:55 AM | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack            | secure-ingress-blueprint
```

**Comment by AjayTripathy** [comment]
cc @linhlam-kc I think that all we need to do is bump to our new chart?

**Comment by linhlam-kc** [comment]
It should work now with the latest version or 0.1.8
`npm install @kubecost/kubecost-eks-blueprints-addon@0.1.8`
Please note that your EKS server must have EBS CSI driver installed as a requirement.

**Comment by elamaran11** [comment]
Thanks @linhlam-kc . One question though. Is the source code in this repo no up to date?

**Comment by chipzoller** [comment]
The EKS anywhere add-on was bumped to 1.106 in [this PR](https://github.com/aws-samples/eks-anywhere-addons/pull/140) so I think this is closed.
